move selectedStory out of redux and into route
opticpower/tracker pull request #37
Opened 2020-10-16 00:50 UTC by shc023

2020-10-16 01:41 UTC, mattvv commented
Gonna test this a bit tomorrow Scott, don't merge yet

2020-10-23 18:49 UTC, mattvv commented
@mikealche this is pretty wildy out of date, but wanted to get your thoughts on why shallow render is still causing all the cards to re-render.

2020-10-29 00:29 UTC, diegofigs approved these changes

2020-10-29 00:29 UTC, diegofigs commented on pages/projects/[id].tsx
> +        setFilters({ ...filters, iteration: filter });
Think you can use type predicates or `[instanceof](https://www.typescriptlang.org/docs/handbook/advanced-types.html#instanceof-type-guards)` operation to type guard
```suggestion
        setFilters({ ...filters, iteration: (filter as Iteration) });
```

2020-10-29 00:29 UTC, diegofigs commented on pages/projects/[id].tsx
> +      setFilters({ ...filters, [name]: getFilterArray(filters[name], filter) });
Same here

2020-10-30 15:06 UTC, mattvv requested changes
just leaving this as request changes until we figure out the performance issue

2021-06-09 17:40 UTC, closed without merging